name: pygbag_build
on: [workflow_dispatch, push]


jobs:  
  build-pygbag:
    name: Build for Emscripten
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python3 -m pip install pygbag
            python3 -m pygbag --ume_block 0 --build $GITHUB_WORKSPACE/main.py
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'build/web'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1